# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.7

EXPOSE 8000

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1

# Install binaries for psycopg2. From https://hub.docker.com/r/tedder42/python3-psycopg2
RUN apt-get update && apt-get install -y --no-install-recommends libpq-dev=11.7-0+deb10u1 gcc=4:8.3.0-1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# need gcc to compile psycopg2

# Install pip requirements
COPY requirements.txt .
RUN python -m pip install -r requirements.txt
RUN python -m pip install coverage
RUN apt-get autoremove -y gcc

# create directory for the app user
RUN mkdir -p /home/app
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/coverage_report
RUN chmod -R +rwx $APP_HOME/coverage_report
RUN mkdir $APP_HOME/static
RUN mkdir $APP_HOME/media
WORKDIR $APP_HOME

COPY . $APP_HOME

#entry point debe hacer collectstatic y ejecutar las migraciones de la db.
COPY init.test.sh .
#COPY wait-for-it.sh .
ENTRYPOINT ["./init.test.sh"]

# NO Switching to a non-root user in github actions
#RUN useradd appuser && chown -R appuser $APP_HOME
#USER appuser

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
#CMD ["gunicorn", "--bind", "0.0.0.0:8000", "storylink_dev.wsgi"]

