# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.7

EXPOSE 8000

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1

# Install pip requirements
COPY requirements.txt .
RUN python -m pip install -r requirements.txt 

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql17 \
    && ACCEPT_EULA=Y apt-get install -y mssql-tools \
    && apt-get update && apt-get install -y unixodbc-dev gcc=4:8.3.0-1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN python -m pip install django-mssql-backend==2.8.1

RUN apt-get autoremove -y gcc

# create directory for the app user
RUN mkdir -p /home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/static
RUN mkdir $APP_HOME/media
WORKDIR $APP_HOME

#ADD . $APP_HOME
#los statics se deben copiar porque el servicio storylinkdev tiene acceso a ellos
#(por el volumen .:/home/app/web), pero el servicio nginx no.
COPY ./static $APP_HOME/static

#entry point debe hacer collectstatic y ejecutar las migraciones de la db.
COPY init.dev.sh .
COPY wait-for-it.sh .
#ENTRYPOINT ["sh", "./init.dev.sh"]

# Switching to a non-root user, please refer to https://aka.ms/vscode-docker-python-user-rights
RUN useradd appuser && chown -R appuser $APP_HOME
USER appuser


# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "storylink_dev.wsgi", "--reload"]

