FROM node:12.18.3

EXPOSE 8080

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./st-front/package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Dont copy, instead use volumes for development 
#COPY ./st-front .

CMD [ "npm", "run", "watch" ]