version: '3.4'

services:
  storylinkdev:
    image: storylinkdev
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    command: bash -c "/home/app/web/wait-for-it.sh --timeout=0 db:5432 && /home/app/web/init.test.sh"
    
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./initdb/initdb.sql:/docker-entrypoint-initdb.d/init-setup.sql
    environment: 
      - POSTGRES_USER=nk_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=nk_db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - storylinkdev
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media

volumes:
  postgres_data:
  static_volume:
  media_volume: