version: "3.4"

services:
  storylinkdev:
    image: storylinkdev_back
    build:
      context: .
      dockerfile: Dockerfile.dev.back
    #depends_on:
    # - db
    volumes:
      - .:/home/app/web
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    #command: bash -c "/home/app/web/wait-for-it.sh --timeout=0 db:5432 && /home/app/web/init.dev.sh"

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./initdb/initdb.sql:/docker-entrypoint-initdb.d/init-setup.sql
    env_file:
      - .env
    ports:
      - 5432:5432
  
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - storylinkdev
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media

volumes:
  postgres_data:
  static_volume:
  media_volume:
