# Generated by Django 3.0.6 on 2020-06-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnsubscribeMassiveMail',
        ),
    ]
