# Generated by Django 2.2 on 2019-04-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuationStoryPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=45)),
                ('user_lastname', models.CharField(max_length=45)),
                ('text_content', models.TextField()),
                ('img_content_link', models.URLField(max_length=500)),
                ('privacity', models.IntegerField()),
                ('date_time', models.DateField()),
                ('views', models.IntegerField()),
                ('valoration', models.IntegerField()),
                ('genre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='HasContinuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('quest_answ', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HasContinuation_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('quest_answ', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=45)),
                ('creation_date_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ResourcePublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=45)),
                ('user_lastname', models.CharField(max_length=45)),
                ('own_user_link', models.CharField(max_length=500)),
                ('link_pub', models.CharField(max_length=500)),
                ('text_content', models.TextField()),
                ('img_content_link', models.URLField(max_length=500)),
                ('privacity', models.IntegerField()),
                ('date_time', models.DateField()),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StoryPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=45)),
                ('user_lastname', models.CharField(max_length=45)),
                ('text_content', models.TextField()),
                ('img_content_link', models.URLField(max_length=500)),
                ('privacity', models.IntegerField()),
                ('date_time', models.DateField()),
                ('views', models.IntegerField()),
                ('valoration', models.IntegerField()),
                ('genre', models.CharField(max_length=45)),
                ('hashtag', models.ManyToManyField(to='publications.Hashtag')),
            ],
        ),
    ]
