# Generated by Django 2.2 on 2019-04-28 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypublication',
            name='own_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcepublication',
            name='hashtag',
            field=models.ManyToManyField(to='publications.Hashtag'),
        ),
        migrations.AddField(
            model_name='resourcepublication',
            name='own_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hascontinuation_2',
            name='contStory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont2Pre', to='publications.ContinuationStoryPublication'),
        ),
        migrations.AddField(
            model_name='hascontinuation_2',
            name='preStory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre2Cont', to='publications.ContinuationStoryPublication'),
        ),
        migrations.AddField(
            model_name='hascontinuation',
            name='baseStory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.StoryPublication'),
        ),
        migrations.AddField(
            model_name='hascontinuation',
            name='contStory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.ContinuationStoryPublication'),
        ),
        migrations.AddField(
            model_name='continuationstorypublication',
            name='hashtag',
            field=models.ManyToManyField(to='publications.Hashtag'),
        ),
        migrations.AddField(
            model_name='continuationstorypublication',
            name='own_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hascontinuation_2',
            unique_together={('preStory', 'contStory')},
        ),
        migrations.AlterUniqueTogether(
            name='hascontinuation',
            unique_together={('baseStory', 'contStory')},
        ),
    ]
