# Generated by Django 2.2 on 2019-11-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20191001_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepublication',
            name='img_content_link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='storypublication',
            name='img_content_link',
            field=models.CharField(max_length=500),
        ),
    ]
