# Generated by Django 2.2 on 2019-11-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20191127_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepublication',
            name='valoration',
            field=models.IntegerField(default=0),
        ),
    ]
