# Generated by Django 2.2 on 2019-12-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_resourcepublication_valoration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storypublication',
            name='genre',
        ),
    ]
