# Generated by Django 2.2 on 2020-03-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20200328_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hascontinuation',
            name='quest_answ',
        ),
    ]
