# Generated by Django 2.2 on 2020-03-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_remove_hascontinuation_quest_answ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storypublication',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='hascontinuation',
            name='quest_answ',
            field=models.CharField(default='old_answ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storypublication',
            name='img_content_link',
            field=models.ImageField(default='gallery/no-img.png', upload_to='gallery/publications/'),
        ),
    ]
