# Generated by Django 2.2 on 2020-03-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20200330_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypublication',
            name='first_story',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
