# Generated by Django 2.2 on 2020-04-02 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0010_storypublication_first_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('date_time', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('valoration', models.IntegerField(default=0)),
                ('quest_answ', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='storypublication',
            name='first_story',
        ),
        migrations.RemoveField(
            model_name='storypublication',
            name='storyContinuation',
        ),
        migrations.AlterField(
            model_name='storypublication',
            name='own_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HasContinuation',
        ),
        migrations.AddField(
            model_name='storychapter',
            name='mainStory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.StoryPublication'),
        ),
        migrations.AddField(
            model_name='storychapter',
            name='own_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storychapter',
            name='prevChapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='publications.StoryChapter'),
        ),
        migrations.AddField(
            model_name='storychapter',
            name='tag',
            field=models.ManyToManyField(to='publications.Tag'),
        ),
    ]
