# Generated by Django 2.2 on 2020-04-15 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_auto_20200402_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storychapter',
            name='prevChapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='publications.StoryChapter'),
        ),
        migrations.AlterField(
            model_name='storychapter',
            name='text_content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='storypublication',
            name='text_content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='storypublication',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=80),
        ),
    ]
