# Generated by Django 2.2 on 2020-04-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_auto_20200415_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypublication',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
