# Generated by Django 2.2 on 2020-04-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_storypublication_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storypublication',
            old_name='privacity',
            new_name='opened',
        ),
    ]
