# Generated by Django 2.2 on 2020-05-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_auto_20200427_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypublication',
            name='color',
            field=models.CharField(default='#4a4a4a', max_length=7),
        ),
    ]
