# Generated by Django 2.2 on 2020-05-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_auto_20200505_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepublication',
            name='own_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='storychapter',
            name='own_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='storypublication',
            name='own_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.UserProfile'),
        ),
    ]
