# Generated by Django 3.0.6 on 2020-05-08 15:58

import apps.publications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_auto_20200506_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypublication',
            name='img_content_link',
            field=models.ImageField(default='gallery/no-img.png', upload_to=apps.publications.models.get_upload_path),
        ),
    ]
