# Generated by Django 2.2.12 on 2020-05-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_customuser_email_verified'),
        ('publications', '0017_auto_20200508_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeToStory', to='users.UserProfile')),
                ('to_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyLikedBy', to='publications.StoryPublication')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeToChapter', to='users.UserProfile')),
                ('to_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapterLikedBy', to='publications.StoryChapter')),
            ],
        ),
        migrations.AddField(
            model_name='storychapter',
            name='like',
            field=models.ManyToManyField(related_name='chapterLikes', through='publications.ChapterLike', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='storypublication',
            name='like',
            field=models.ManyToManyField(related_name='storyLikes', through='publications.StoryLike', to='users.UserProfile'),
        ),
    ]
