# Generated by Django 3.0.6 on 2020-05-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0018_auto_20200510_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='storychapter',
            name='privated',
            field=models.BooleanField(default=False, verbose_name='privada'),
        ),
        migrations.AddField(
            model_name='storypublication',
            name='privated',
            field=models.BooleanField(default=False, verbose_name='privada'),
        ),
    ]
