# Generated by Django 3.0.6 on 2020-05-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0019_auto_20200524_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storychapter',
            name='privated',
        ),
    ]
