# Generated by Django 3.0.6 on 2020-05-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0020_remove_storychapter_privated'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypublication',
            name='status',
            field=models.CharField(choices=[('WR', 'Leer y Continuar'), ('R', 'Solo leer'), ('NR', 'No ver')], default='WR', max_length=2),
        ),
    ]
