# Generated by Django 3.0.6 on 2020-05-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0021_storypublication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storypublication',
            name='opened',
        ),
        migrations.RemoveField(
            model_name='storypublication',
            name='privated',
        ),
        migrations.AlterField(
            model_name='storypublication',
            name='status',
            field=models.CharField(choices=[('WR', 'Leer y Continuar: permite que otros usuarios puedan leer la publicación y continuar la trama.'), ('R', 'Solo leer: permite que otros usuarios solo puedan leer la publicación.'), ('NR', 'No ver: solo tú podrás ver esta publicación.')], default='WR', max_length=2),
        ),
    ]
