# Generated by Django 2.2 on 2019-09-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190507_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default='Aname', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
