# Generated by Django 2.2 on 2019-09-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190917_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubsubscriptionmodelaux',
            name='date_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userevents',
            name='date_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usersubscriptionmodelaux',
            name='date_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
