# Generated by Django 2.2 on 2019-11-27 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190930_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubsubscriptionmodelaux',
            name='pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub2User', to='publications.StoryPublication'),
        ),
        migrations.AlterField(
            model_name='pubsubscriptionmodelaux',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2Pub', to=settings.AUTH_USER_MODEL),
        ),
    ]
