# Generated by Django 2.2 on 2020-05-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200505_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_link_img_perfil',
            field=models.CharField(default='gallery/no-img-profile.png', max_length=350),
        ),
    ]
