# Generated by Django 2.2 on 2020-05-05 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userprofile_full_link_img_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_link_img_perfil',
        ),
    ]
