# Generated by Django 2.2 on 2020-05-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_userprofile_full_link_img_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
