# Generated by Django 3.0.6 on 2020-05-24 13:12

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_customuser_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=35, unique=True, validators=[apps.users.models.unique_user], verbose_name='Nombre de usuario'),
        ),
    ]
