# Generated by Django 3.0.6 on 2020-06-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0002_delete_unsubscribemassivemail'),
        ('users', '0021_auto_20200524_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cat_unsubscribed',
            field=models.ManyToManyField(related_name='unsubscribeMail', to='site_manager.Category'),
        ),
    ]
