# Generated by Django 3.0.6 on 2020-06-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0002_delete_unsubscribemassivemail'),
        ('users', '0022_userprofile_cat_unsubscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cat_unsubscribed',
            field=models.ManyToManyField(null=True, related_name='unsubscribeMail', to='site_manager.Category'),
        ),
    ]
