# Generated by Django 3.0.6 on 2020-06-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0002_delete_unsubscribemassivemail'),
        ('users', '0023_auto_20200616_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cat_unsubscribed',
            field=models.ManyToManyField(blank=True, null=True, related_name='unsubscribeMail', to='site_manager.Category'),
        ),
    ]
