name: CI

on:
  push:
    branches: [ master, react_webp_redux, dockerizando ]
  pull_request:
    branches: [ master ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose -f docker-compose.test.yml build
    - name: Run Docker image
      run: docker-compose -f docker-compose.test.yml run --no-deps --rm storylinkdev --tag test:$(date +%s)
      env: 
        DEBUG: ${{ secrets.DEBUG }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SOCIAL_AUTH_FACEBOOK_KEY: ${{ secrets.SOCIAL_AUTH_FACEBOOK_KEY }}
        SOCIAL_AUTH_FACEBOOK_SECRET: ${{ secrets.SOCIAL_AUTH_FACEBOOK_SECRET }}
        SOCIAL_AUTH_TWITTER_KEY: ${{ secrets.SOCIAL_AUTH_TWITTER_KEY }}
        SOCIAL_AUTH_TWITTER_SECRET: ${{ secrets.SOCIAL_AUTH_TWITTER_SECRET }}
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-storylink
        fail_ci_if_error: true