name: Docker Image CI

on:
  push:
    branches: [ master, react_webp_redux, dockerizando ]
  pull_request:
    branches: [ master ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up build -f "docker-compose.test.yml" --tag test:$(date +%s)
